apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-4
  labels:
    type: local
spec:
  storageClassName: gold
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/tmp/data"
