version: "3"

services:
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    ports:
        - 8000:8000
    
  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3
    ports:
      - 8001:8001
      - 8003:8003
      - 8080:8080

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:3
    ports:
      - 1701:1700/udp

  chirpstack-geolocation-server:
    image: chirpstack/chirpstack-geolocation-server:3
    ports:
        - 8005:8005

  postgresql:
    image: postgres:alpine
    ports:
        - 5432:5432
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:5-alpine
    ports:
        - 6379:6379
    volumes:
      - redisdata:/data

  mosquitto:
    image: eclipse-mosquitto
    ports:
        - 1883:1883

volumes:
  postgresqldata:
  redisdata:

