apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: chirpstack-application-server
  name: chirpstack-application-server
spec:
  type: LoadBalancer
  ports:
  - name: "8001"
    port: 8001
    targetPort: 8001
  - name: "8003"
    port: 8003
    targetPort: 8003
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    io.kompose.service: chirpstack-application-server
status:
  loadBalancer: {}
