apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gateway-bridge
data:
  chirpstack-gateway-bridge.toml: |
    [integration.mqtt.auth.generic]
    servers=["tcp://mosquitto:1883"]
    username=""
    password=""
